import { Review } from "../types";

export const DATA: Review[] = [
  {
    id: "1",
    repId: "rep-1",
    managerId: "manager-1",
    name: "Omar Al‑Harbi",
    initials: "OA",
    role: "Supervisor",
    email: "omar.alharbi@golderapharm.com",
    department: "Sales",
    location: "Riyadh",
    period: "Q3 2025",
    statusBadge: "Excellent",
    lastReview: "Sep 30, 2025",
    overallCurrent: 92,
    overallPrevious: 88,
    managerName: "Regional Manager",
    kpis: [
      { label: "Sales Performance", value: 95 },
      { label: "Customer Relationships", value: 90 },
      { label: "Product Knowledge", value: 88 },
      { label: "Compliance & Regulations", value: 94 },
      { label: "Teamwork & Collaboration", value: 89 },
    ],
    feedbackComments:
      "Excellent performance across all metrics. Keep up the great work!",
  },
  {
    id: "2",
    repId: "rep-2",
    managerId: "manager-1",
    name: "Layla Al‑Zahrani",
    initials: "LA",
    role: "Supervisor",
    email: "layla.alzahrani@golderapharm.com",
    department: "Sales",
    location: "Jeddah",
    period: "Q3 2025",
    statusBadge: "Good",
    lastReview: "Oct 20, 2025",
    overallCurrent: 78,
    overallPrevious: 79,
    managerName: "Regional Manager",
    kpis: [
      { label: "Sales Performance", value: 80 },
      { label: "Customer Relationships", value: 75 },
      { label: "Product Knowledge", value: 78 },
      { label: "Compliance & Regulations", value: 77 },
      { label: "Teamwork & Collaboration", value: 80 },
    ],
  },
  {
    id: "3",
    repId: "rep-3",
    managerId: "manager-1",
    name: "Fahad Al‑Saeed",
    initials: "FA",
    role: "Medical Rep",
    email: "fahad.alsaeed@golderapharm.com",
    location: "Dammam",
    period: "Q1 2025",
    statusBadge: "Improving",
    lastReview: "Mar 12, 2025",
    overallCurrent: 84,
    overallPrevious: 80,
    managerName: "Regional Manager",
    kpis: [
      { label: "Sales Performance", value: 82 },
      { label: "Customer Relationships", value: 86 },
      { label: "Product Knowledge", value: 80 },
      { label: "Compliance & Regulations", value: 84 },
      { label: "Teamwork & Collaboration", value: 88 },
    ],
    feedbackComments:
      "Showing improvement in key areas. Continue focusing on product knowledge.",
  },
  {
    id: "4",
    repId: "rep-4",
    managerId: "manager-1",
    name: "Laila Al‑Qahtani",
    initials: "LQ",
    role: "Medical Rep",
    email: "laila.alqahtani@golderapharm.com",
    department: "Medical Affairs",
    location: "Riyadh",
    period: "Q2 2025",
    statusBadge: "Good",
    lastReview: "Jun 08, 2025",
    overallCurrent: 88,
    overallPrevious: 85,
    managerName: "Regional Manager",
    kpis: [
      { label: "Sales Performance", value: 90 },
      { label: "Customer Relationships", value: 87 },
      { label: "Product Knowledge", value: 89 },
      { label: "Compliance & Regulations", value: 88 },
      { label: "Teamwork & Collaboration", value: 86 },
    ],
  },
];
